# Generated by Django 4.2.7 on 2023-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qa_datasheet_first_mueller_hinton_agar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_code', models.CharField(max_length=50)),
                ('Lot_No', models.CharField(max_length=100)),
                ('mfg_data', models.DateField(auto_now_add=True)),
                ('Expiry_date', models.DateField()),
                ('Appearance_res', models.CharField(max_length=150)),
                ('Appearance_theory', models.CharField(max_length=150)),
                ('color_res', models.CharField(max_length=100)),
                ('color_theory', models.CharField(max_length=100)),
                ('ph_res', models.CharField(max_length=50)),
                ('micro_biology_activity_res', models.CharField(max_length=100)),
                ('Streptococcus_pyogenes_ATCC_19615_res', models.CharField(max_length=100)),
                ('Streptococcus_pneumoniae_ATCC_6305_res', models.CharField(max_length=150)),
                ('Staphylococcus_aureus_ATCC_25923_res', models.CharField(max_length=150)),
                ('Escherichia_coli_ATCC_25922_res', models.CharField(max_length=150)),
            ],
        ),
    ]
