# Generated by Django 4.2.7 on 2023-12-05 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_qa_datasheet_first_mueller_hinton_agar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Escherichia_coli_ATCC_25922_res',
        ),
        migrations.RemoveField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Staphylococcus_aureus_ATCC_25923_res',
        ),
        migrations.RemoveField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Streptococcus_pneumoniae_ATCC_6305_res',
        ),
        migrations.RemoveField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Streptococcus_pyogenes_ATCC_19615_res',
        ),
        migrations.RemoveField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='ph_res',
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Ampicillin_10_ug_zone_size',
            field=models.CharField(choices=[('16 mm', '16 mm'), ('17 mm', '17 mm'), ('18 mm', '18 mm'), ('19 mm', '19 mm'), ('20 mm', '20 mm'), ('21 mm', '21 mm'), ('22 mm', '22 mm')], default='16 mm', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Ciprofloxacin_15μg_zone_size',
            field=models.CharField(choices=[('16 mm', '16 mm'), ('17 mm', '17 mm'), ('18 mm', '18 mm'), ('19 mm', '19 mm'), ('20 mm', '20 mm'), ('21 mm', '21 mm'), ('22 mm', '22 mm')], default='16 mm', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Enterococcus_faecalis_ATCC_29212_Antiboitic',
            field=models.CharField(default='Trimethoprim sulfamethoxazole 1.25/23.μg  & Vancomycin 5μg', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Escherichia_coli_ATCC_25922_Antibiotic',
            field=models.CharField(default='Ampicillin 10 ug', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Linezolid_10μg_zone_size',
            field=models.CharField(choices=[('21 mm', '21 mm'), ('22 mm', '22 mm'), ('23 mm', '23 mm'), ('24 mm', '24 mm'), ('25 mm', '25 mm'), ('26 mm', '26 mm'), ('27 mm', '27 mm')], default='16 mm', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Microbiological_state',
            field=models.CharField(default='CONFORME', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Pseudomonas_aeruginosa_ATCC_27853_Antiboitic',
            field=models.CharField(default='Ciprofloxacin 15μg', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Staphylococcus_aureus_ATCC_29213_Antiboitic',
            field=models.CharField(default='Linezolid 10μg', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Trimethoprim_sulfamethoxazole_125_23_μg_zone_size',
            field=models.CharField(choices=[('16 mm', '16 mm'), ('17 mm', '17 mm'), ('18 mm', '18 mm'), ('19 mm', '19 mm'), ('20 mm', '20 mm'), ('21 mm', '21 mm'), ('22 mm', '22 mm')], default='16 mm', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Vancomycin_5μg_zone_size',
            field=models.CharField(choices=[('16 mm', '16 mm'), ('17 mm', '17 mm'), ('18 mm', '18 mm'), ('19 mm', '19 mm'), ('20 mm', '20 mm'), ('21 mm', '21 mm'), ('22 mm', '22 mm')], default='16 mm', max_length=250),
        ),
        migrations.AddField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='pH_value',
            field=models.CharField(choices=[('7', '7'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('7.5', '7.5'), ('7.6', '7.6')], default='7.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Appearance_res',
            field=models.CharField(default='CONFORME', max_length=150),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Appearance_theory',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Lot_No',
            field=models.CharField(default='MP06', max_length=100),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='Material_code',
            field=models.CharField(default='MP06', max_length=50),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='color_res',
            field=models.CharField(default='CONFORME', max_length=100),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='color_theory',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='mfg_data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='qa_datasheet_first_mueller_hinton_agar',
            name='micro_biology_activity_res',
            field=models.CharField(choices=[('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37')], default='35', max_length=100),
        ),
    ]
