# Generated by Django 4.2.7 on 2023-12-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_qa_datasheet_mueller_hinton_agar_delete_qa_datasheet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa_datasheet_mueller_hinton_agar',
            options={'verbose_name_plural': 'MUELLER HINTON AGAR Q.C'},
        ),
    ]
